import catchErrors from "../utils/catchErrors";

export const getAgentContacts = catchErrors(async (req, res) => {});
export const getContactById = catchErrors(async (req, res) => {});
export const createAgentContact = catchErrors(async (req, res) => {});
export const createLead = catchErrors(async (req, res) => {});
export const updateAgentContact = catchErrors(async (req, res) => {});
